{% set name = "signalrcore" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/signalrcore-{{ version }}.tar.gz
  sha256: d42258344202c1f861d7c361c62d4d0d147d839b52d1a02d52426b694a14ef00

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.22.0
    - websocket-client >=0.54.0
    - msgpack-python >=1.0.0

test:
  imports:
    - signalrcore
    - signalrcore.hub
    - signalrcore.messages
    - signalrcore.protocol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mandrewcito/signalrcore
  summary: A Python SignalR Core client, with invocation auth and two way streaming. Compatible with azure / serverless functions. Also with automatic reconnect and manually reconnect.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
