{% set name = "signalrcore" %}
{% set version = "0.8.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/signalrcore-{{ version }}.tar.gz
  sha256: 20f19f2cc606aa09e3c6429cf0f3b474789835ddd1d062c218ae0c13aa0db673

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests >=2.22.0
    - websocket-client >=0.54.0

test:
  imports:
    - signalrcore
    - signalrcore.hub
    - signalrcore.messages
    - signalrcore.protocol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mandrewcito/signalrcore
  summary: A Python SignalR Core client, with invocation auth and two way streaming. Compatible with azure / serverless functions. Also with automatic reconnect and manually reconnect.
  license: MIT
  license_family: MIT
  # License file manually packaged. See: https://github.com/mandrewcito/signalrcore/pull/33
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
