schema_version: 1

context:
  name: signalrcore
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/signalrcore-${{ version }}.tar.gz
  sha256: e767750eb52ad0a07746686cef8bc68e5832168069b5c43c477be2a68fd1e44c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - msgpack-python ==1.0.2

tests:
  - python:
      imports:
        - signalrcore
        - signalrcore.hub
        - signalrcore.messages
        - signalrcore.protocol
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A Python SignalR Core client, with invocation auth and two way streaming. Compatible with azure / serverless functions. Also with automatic reconnect and manually reconnect.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mandrewcito/signalrcore

extra:
  recipe-maintainers:
    - synapticarbors
